create table student.ay_query_crew_attempt_test
("ID" int,
"Purchase-date" date,
"Date" varchar(15),
"Time" varchar(23),
"Quarter" varchar(11),
"Qtr" varchar(4),
"Year" int, 
"Month" int,
"Date_1" int, 
"Special Day" int,
"Online Sale Offers " int,
"Day" int,
"Weekend" int,
"Morning" int,
"Afternoon" int, 
"Evening" int, 
"Night" int,
"Gender" int,
"Customer ID" varchar(200), 
"Gender F=1665 M=1815" varchar(13),
"Product-Name" varchar(156),
"Item-Status" varchar(10),
"Quantity" int, 
"Currency" varchar(5),
"Item Price" float, 
"Shipping-Price" float, 
"Ship-City" varchar(52),
"Ship-State" varchar(28),
"Ship-Postal-Code" varchar(9),
"Category" varchar(15),
"Total_amount" float, 
"Author" varchar(54),
"Publication" varchar(62),
"Profit Percentage (%)" float,
"Profit (INR)" float,
"Cost Price" float);

